app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="app_index"),
    path("face-login/", views.face_login, name="face_login"),
    path("register/", views.register, name="register"),
]

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("registration-fields/", views.registration_fields, name="registration_fields"),
    path("people/", views.people_view, name="people"),
    path("logs/", views.logs_view, name="logs"),
    path("blacklist/", views.blacklist, name="blacklist"),
    path("notifications/", views.notifications_view, name="notifications"),
    path("delete-person/<person_id>/", views.delete_person, name="delete_person"),
]

identiv/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("developer-admin/", admin.site.urls),
    path("", include("onboarding.urls")),
    path("app/", include("app.urls")),
    path("dashboard/", include("dashboard.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Developer Admin"
admin.site.site_title = "Developer Admin Portal"
admin.site.index_title = "Welcome to Developer Admin Portal of Identiv"

dashboard/models.py
import uuid
from django.db import models
from app.models import Person, Organization


# Create your models here.
class LoginLog(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="login_logs"
    )
    login_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.login_time.strftime('%Y-%m-%d %H:%M:%S')} by {self.person.first_name} {self.person.last_name} from {self.organization.organization_name}"

    class Meta:
        unique_together = (
            "person",
            "organization",
            "login_time",
        )  # Ensure unique person and time entry


class CustomField(models.Model):
    FIELD_TYPES = (
        ("Text", "Text"),
        ("BigText", "BigText"),
        ("Radio", "Radio"),
        ("Checkbox", "Checkbox"),
    )
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="custom_fields"
    )
    name = models.CharField(max_length=100)
    field_type = models.CharField(max_length=50, choices=FIELD_TYPES, default="Text")

    def __str__(self):
        return (
            f"{self.name} ({self.field_type}) for {self.organization.organization_name}"
        )


class Option(models.Model):
    custom_field = models.ForeignKey(
        CustomField, on_delete=models.CASCADE, related_name="options"
    )
    option_name = models.CharField(max_length=100)

    def __str__(self):
        return f"Option: {self.option_name} | Field: {self.custom_field.name}"


class PersonDetail(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name="person_detail"
    )
    custom_field = models.ForeignKey(CustomField, on_delete=models.CASCADE)
    response_text = models.TextField(
        null=True, blank=True
    )  # For Text and BigText responses
    selected_options = models.ManyToManyField(Option, blank=True)  # For Radio/Checkbox

    class Meta:
        unique_together = ("person", "custom_field")

    def __str__(self):
        return f"Response of {self.person.first_name} {self.person.last_name} to {self.custom_field.name} from {self.custom_field.organization.organization_name}"


class Notification(models.Model):
    PENDING = "Pending"
    ACCEPTED = "Accepted"
    REJECTED = "Rejected"

    STATUS_CHOICES = [
        (PENDING, "Pending"),
        (ACCEPTED, "Accepted"),
        (REJECTED, "Rejected"),
    ]

    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PENDING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Notification for {self.organization} from {self.person}"


class Blacklist(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    blacklisted_on = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Blacklisted {self.person} from {self.organization}"

    class Meta:
        verbose_name_plural = "Blacklisted People"

dashboard/forms.py
from django import forms
from .models import CustomField, Option


class CustomFieldForm(forms.ModelForm):
    class Meta:
        model = CustomField
        fields = ["name", "field_type"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"class": "input"})
        self.fields["field_type"].widget.attrs.update({"class": "select"})


class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ["option_name"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["option_name"].widget.attrs.update({"class": "input is-small"})

dashboard/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import posthog

from app.models import Person
from dashboard.forms import CustomFieldForm, OptionForm
from dashboard.models import Blacklist, CustomField, Notification, Option, PersonDetail


# Create your views here.
@login_required
def registration_fields(request):
    """
    Handle form submission for creating custom fields and adding options to them.
    """
    # Initialize the forms
    custom_field_form = CustomFieldForm()
    option_form = OptionForm()
    edit_field_instance = None  # To track the field being edited

    posthog.capture(request.user.uid, "$pageview")

    if request.method == "POST":
        # Handle form submission for creating a new custom field
        if "create_field" in request.POST:
            custom_field_form = CustomFieldForm(request.POST)
            if custom_field_form.is_valid():
                custom_field = custom_field_form.save(commit=False)
                custom_field.organization = (
                    request.user
                )  # Assign the current organization
                custom_field.save()
                posthog.capture(
                    request.user.uid,  # The unique identifier of the user (can be the user's ID or email)
                    "dashboard:organization:create_custom_field",  # The event name
                    {
                        "organization_name": request.user.organization_name,
                        "custom_field_id": custom_field.uid,
                        "custom_field_name": custom_field.name,
                        "custom_field_type": custom_field.field_type,
                    },
                )
                return redirect("registration_fields")  # Redirect to the same view

        # Handle form submission for adding options to a custom field
        elif "add_option" in request.POST:
            field_id = request.POST.get(
                "field_id"
            )  # Get the field ID from a hidden input
            custom_field = get_object_or_404(
                CustomField, uid=field_id, organization=request.user
            )
            option_form = OptionForm(request.POST)
            if option_form.is_valid():
                option = option_form.save(commit=False)
                option.custom_field = (
                    custom_field  # Link the option to the custom field
                )
                option.save()
                posthog.capture(
                    request.user.uid,  # The unique identifier of the user (can be the user's ID or email)
                    "dashboard:organization:create_option_for_custom_field",  # The event name
                    {
                        "organization_name": request.user.organization_name,
                        "custom_field_id": custom_field.uid,
                        "custom_field_name": custom_field.name,
                        "custom_field_type": custom_field.field_type,
                        "option_id": option.id,
                        "option_name": option.option_name,
                    },
                )
                return redirect("registration_fields")  # Redirect to the same view

        # Handle deleting a custom field
        elif "delete_field" in request.POST:
            field = get_object_or_404(CustomField, uid=request.POST["field_id"])
            posthog.capture(
                request.user.uid,  # The unique identifier of the user (can be the user's ID or email)
                "dashboard:organization:delete_custom_field",  # The event name
                {
                    "organization_name": request.user.organization_name,
                    "custom_field_id": field.uid,
                    "custom_field_name": field.name,
                    "custom_field_type": field.field_type,
                },
            )
            field.delete()
            return redirect("registration_fields")

        # Handle deleting an option
        elif "delete_option" in request.POST:
            option = get_object_or_404(Option, id=request.POST["option_id"])
            posthog.capture(
                request.user.uid,  # The unique identifier of the user (can be the user's ID or email)
                "dashboard:organization:delete_option_for_custom_field",  # The event name
                {
                    "organization_name": request.user.organization_name,
                    "option_id": option.id,
                    "option_name": option.option_name,
                },
            )
            option.delete()
            return redirect("registration_fields")

        # Handle editing a custom field
        elif "edit_field" in request.POST:
            field = get_object_or_404(CustomField, uid=request.POST["field_id"])
            custom_field_form = CustomFieldForm(request.POST, instance=field)
            if custom_field_form.is_valid():
                custom_field_form.save()
                posthog.capture(
                    request.user.uid,  # The unique identifier of the user (can be the user's ID or email)
                    "dashboard:organization:edit_custom_field",  # The event name
                    {
                        "organization_name": request.user.organization_name,
                        "custom_field_id": custom_field.uid,
                        "custom_field_name": custom_field.name,
                        "custom_field_type": custom_field.field_type,
                    },
                )
                return redirect("registration_fields")

    # Fetch custom fields created by the logged-in organization
    custom_fields = CustomField.objects.filter(organization=request.user)
    custom_field_form = CustomFieldForm(instance=edit_field_instance)

    context = {
        "custom_field_form": custom_field_form,
        "option_form": option_form,
        "custom_fields": custom_fields,
        "edit_field_instance": edit_field_instance,  # Pass the field being edited
    }

    # Render the page with the forms and custom fields
    return render(
        request,
        "dashboard/registration_fields.html",  # Make sure the template path matches your folder structure
        context,
    )


@login_required
def people_view(request):
    search_query = request.GET.get("search", "")
    filters = {}

    posthog.capture(request.user.uid, "$pageview")

    # Iterate over GET parameters to capture selected filters
    for key, value in request.GET.items():
        if key != "search" and value:
            filters[key] = value

    # Get current organization
    organization = request.user

    # Fetch people from the same organization and apply search filter
    people = organization.people.filter(
        Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query)
    ).prefetch_related("person_detail__custom_field", "person_detail__selected_options")

    # Apply custom field filters
    for field_name, option_value in filters.items():
        people = people.filter(
            person_detail__custom_field__name=field_name,
            person_detail__selected_options__option_name=option_value,
        )

    # Create a dictionary to store person details efficiently
    people_details = PersonDetail.objects.filter(
        person__in=people, custom_field__organization=organization
    )

    context = {
        "people": people,
        "people_details": people_details,
        "custom_fields": organization.custom_fields.filter(
            field_type__in=["Radio", "Checkbox"]
        ),
    }
    return render(request, "dashboard/people.html", context)


@login_required
def logs_view(request):
    search_query = request.GET.get("search", "").strip()
    organization = (
        request.user
    )  # Assuming the logged-in user belongs to one organization

    posthog.capture(request.user.uid, "$pageview")

    # Access people related to the current organization through the Many-to-Many relationship
    if search_query:
        # Filter people based on first name or last name and ensure they belong to the current organization
        logs = organization.login_logs.filter(
            Q(person__first_name__icontains=search_query)
            | Q(person__last_name__icontains=search_query)
        ).order_by("-login_time")
    else:
        # If no search query, show all people from the current organization
        logs = organization.login_logs.all().order_by("-login_time")

    context = {"logs": logs, "search_query": search_query}
    return render(request, "dashboard/logs.html", context)


@login_required
def notifications_view(request):
    notifications = Notification.objects.filter(organization=request.user)

    posthog.capture(request.user.uid, "$pageview")

    if request.method == "POST":
        notification_id = request.POST["notification_id"]
        decision = request.POST["decision"]
        notification = get_object_or_404(Notification, uid=notification_id)

        if decision == "approve":
            # Add the person to the organization and approve their membership in this specific org
            notification.organization.people.add(notification.person)
            notification.person.is_active = True  # Mark as approved for this org
            notification.person.save()
            posthog.capture(
                notification.person.uid,  # The unique identifier of the user (can be the user's ID or email)
                "dashboard:person:registration_request_approved",  # The event name
                {
                    "first_name": notification.person.first_name,
                    "middle_name": notification.person.middle_name,
                    "last_name": notification.person.last_name,
                    "organization_name": request.user.organization_name,
                },
            )

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} Dashboard | Identiv</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <!-- Bulma CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">

    <link rel="stylesheet" href="{% static 'dashboard/style.css' %}">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body>
    {% include 'dashboard/partials/navbar.html' %}

    {% block body %}{% endblock %}

    <script src="{% static 'dashboard/main.js' %}"></script>
</body>

</html>

dashboard/templates/dashboard/blacklist.html
{% extends 'dashboard/base.html' %}

{% block title %}
Blacklist
{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title">Blacklist</h1>
        <form method="GET" action="">
            <div class="field has-addons">
                <div class="control has-icons-left is-expanded">
                    <input class="input" type="text" name="search" value="{{ search_query }}"
                        placeholder="Search by first or last name...">
                    <span class="icon is-left">
                        <i class="fas fa-search"></i>
                    </span>
                </div>
                <div class="control">
                    <button type="submit" class="button is-primary">Search</button>
                </div>
            </div>
        </form>

        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Blacklisted on</th>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for blacklisted_person in blacklist %}
                <tr>
                    <td>{{ blacklisted_person.blacklisted_on }}</td>
                    <td>{{ blacklisted_person.person.first_name }}</td>
                    <td>{{ blacklisted_person.person.middle_name }}</td>
                    <td>{{ blacklisted_person.person.last_name }}</td>
                    <td>
                        <form action="{% url 'delete_person' blacklisted_person.person.uid %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="button is-danger is-small">Delete</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Nobody blacklisted.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

dashboard/templates/dashboard/logs.html
{% extends 'dashboard/base.html' %}

{% block title %}
Login Logs
{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title">Login Logs</h1>
        <form method="GET" action="">
            <div class="field has-addons">
                <div class="control has-icons-left is-expanded">
                    <input class="input" type="text" name="search" value="{{ search_query }}"
                        placeholder="Search by first or last name...">
                    <span class="icon is-left">
                        <i class="fas fa-search"></i>
                    </span>
                </div>
                <div class="control">
                    <button type="submit" class="button is-primary">Search</button>
                </div>
            </div>
        </form>

        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{ log.login_time }}</td>
                    <td>{{ log.person.first_name }}</td>
                    <td>{{ log.person.middle_name }}</td>
                    <td>{{ log.person.last_name }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Nobody logged in.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

dashboard/templates/dashboard/notifications.html
{% extends 'dashboard/base.html' %}

{% block title %}
Notifications
{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title">Registration Requests</h1>

        {% if notifications %}
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Person</th>
                    <th>Request Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for notification in notifications %}
                <tr>
                    <td>{{ notification.person.first_name }} {{ notification.person.middle_name }}
                        {{ notification.person.last_name }}</td>
                    <td>{{ notification.created_at }}</td>
                    <td>
                        <form method="POST" action="{% url 'notifications' %}">
                            {% csrf_token %}
                            <input type="hidden" name="notification_id" value="{{ notification.uid }}">

                            <div class="buttons">
                                <!-- Approve button -->
                                <button type="submit" name="decision" value="approve"
                                    class="button is-success is-small">
                                    <span class="icon"><i class="fas fa-check"></i></span>
                                    <span>Approve</span>
                                </button>

                                <!-- Reject button -->
                                <button type="submit" name="decision" value="reject" class="button is-danger is-small">
                                    <span class="icon"><i class="fas fa-times"></i></span>
                                    <span>Reject</span>
                                </button>
                            </div>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="notification is-warning">
            No pending registration requests.
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

dashboard/templates/dashboard/people.html
{% extends 'dashboard/base.html' %}

{% load custom_filters %}

{% block title %}
People
{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <div class="columns is-mobile">
            <!-- Search Bar -->
            <div class="column is-12">
                <form method="GET" action="{% url 'people' %}" id="filter-form">
                    <div class="field">
                        <div class="control has-icons-left">
                            <input class="input" type="search" name="search" placeholder="Search by name"
                                value="{{ request.GET.search|default_if_none:'' }}">
                            <span class="icon is-left">
                                <i class="fas fa-search"></i>
                            </span>
                        </div>
                    </div>
                    {% for custom_field in custom_fields %}
                    {% if custom_field.field_type == "Radio" or custom_field.field_type == "Checkbox" %}
                    <div class="field">
                        <label class="label">{{ custom_field.name }}</label>
                        <div class="control">
                            <div class="select">
                                <select name="{{ custom_field.name }}">
                                    <option value="">Select {{ custom_field.name }}</option>
                                    {% for option in custom_field.options.all %}
                                    <option value="{{ option.option_name }}" {% if
                                        request.GET|get_query_param:custom_field.name==option.option_name %} selected {%
                                        endif %}>
                                        {{ option.option_name }}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <button class="button is-primary" type="submit">Filter</button>
                </form>
            </div>
        </div>

        <!-- People list with their details -->
        {% if people %}
        <div class="table-container">
            <table class="table is-fullwidth is-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        {% for detail in people_details %}
                        <th>{{ detail.custom_field.name }}</th>
                        {% endfor %}
                        <th>Active</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for person in people %}
                    <tr>
                        <td>{{ person.first_name }} {{ person.middle_name }} {{ person.last_name }}</td>
                        {% for detail in people_details %}
                        {% if detail.person == person %}
                        <td>
                            {% if detail.response_text %}
                            {{ detail.response_text }}
                            {% elif detail.selected_options.all %}
                            {{ detail.selected_options.all|option_names }}
                            {% endif %}
                        </td>
                        {% endif %}
                        {% endfor %}
                        <td>
                            {% if person.is_active %}
                            <span class="icon has-text-success">
                                <i class="fas fa-check"></i>
                            </span>
                            {% else %}
                            <span class="icon has-text-danger">
                                <i class="fas fa-times"></i>
                            </span>
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'delete_person' person.uid %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="button is-danger is-small">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p>No people found.</p>
        {% endif %}
</section>
{% endblock %}

dashboard/templates/dashboard/registration_fields.html
{% extends 'dashboard/base.html' %}

{% block title %}
Registration Fields
{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title mb-3">Manage Registration Fields</h1>

        <!-- Form to Create a New Custom Field -->
        <h2 class="subtitle">Create Custom Field</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="field">
                <label class="label" for="id_name">Field Name</label>
                <div class="control">
                    {{ custom_field_form.name }}
                </div>
            </div>

            <div class="field">
                <label class="label" for="id_field_type">Field Type</label>
                <div class="control">
                    <div class="select">
                        {{ custom_field_form.field_type }}
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-primary" name="create_field" type="submit">Add Field</button>
                </div>
            </div>
        </form>
        <hr>

        <!-- Existing custom fields and form to add options -->
        <h2 class="subtitle">Existing Custom Fields</h2>
        {% for field in custom_fields %}
        <div class="card">
            <div class="card-content">
                <h3 class="title is-5">{{ field.name }}</h3>
                <p class="subtitle is-6">Type: {{ field.field_type }}</p>

                <!-- Edit Custom Field -->
                <form method="POST" class="edit-field-form">
                    {% csrf_token %}
                    <input type="hidden" name="field_id" value="{{ field.uid }}">
                    <div class="field">
                        <label class="label" for="id_name">Field Name</label>
                        <div class="control">
                            {{ custom_field_form.name }}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label" for="id_field_type">Field Type</label>
                        <div class="control">
                            <div class="select">
                                {{ custom_field_form.field_type }}
                            </div>
                        </div>
                    </div>

                    <button type="submit" name="edit_field" class="button is-info">Edit Field</button>
                </form>

                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="field_id" value="{{ field.uid }}">
                    <button type="submit" name="delete_field" class="button is-danger">Delete Field</button>
                </form>
                {% if field.field_type in "Radio Checkbox" %}
                <hr>
                <ul>
                    {% for option in field.options.all %}
                    <li>{{ option.option_name }}</li>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="option_id" value="{{ option.id }}">
                        <button type="submit" name="delete_option" class="button is-danger is-small">Delete
                            Option</button>
                    </form>
                    {% empty %}
                    <li>No options added yet.</li>
                    {% endfor %}
                </ul>
                <form method="POST" class="option-form">
                    {% csrf_token %}
                    <input type="hidden" name="field_id" value="{{ field.uid }}">
                    {{ option_form.as_p }}
                    <button type="submit" name="add_option" class="button is-info is-small my-3">Add
                        Option</button>
                </form>
                {% endif %}
            </div>
        </div>
        {% endfor %}
</section>
{% endblock %}